### PR TITLE
Add Cask support for better out-of-the-box batch experience

### PR DESCRIPTION
**Pull request by Fuco1**
Cask makes it really easy to run binaries with the proper load-paths and all. 

It manages the dependencies independently of the user's config so it won't break your shell scripts randomly if you happen to update your .emacs.d.

Out of the box usage is as simple as `cask install`, `cask exec org-clock-csv <file>`

If this is merged then the melpa recipe should probably be also updated to include the bin directory.

### CODE REVIEW

**Comment by atheriel** [comment]
I'm happy to support additional methods of using the package. However, I'm not familiar with Cask at all, so permit me some questions. (1) Will this affect vanilla Emacs users in any way, or is it strictly opt-in? and (2) why would the MELPA recipe need to be updated?

**Comment by Fuco1** [comment]
1) It's completely optional.
2) Because I've added the `bin` directory with a "binary" (shell script---which can also be used without cask, you will just need to pass the load-path manually as you describe in the readme).  This is not picked up by the default melpa fetcher.

**Comment by atheriel** [comment]
Ah, I see the `bin` addition now. What does the installation process look like for Cask "binaries" from MELPA? (This would be nice to add to the README.)

Edit: I should read more carefully. What I mean is, will `cask install` work if and only if we add `bin/*` to the MELPA recipe?

**Comment by Fuco1** [comment]
The install will work in any case but the shell script won't be present because it won't be packaged up by MELPA.

If the bin is in the recipe then the package downloaded from MELPA will have a bin directory which cask can automatically locate and add to the exec path.

**Comment by atheriel** [comment]
Thanks for your patience. Feel free to update the MELPA recipe if you have the time -- you can link to this issue (or this comment) if they need permission from the maintainer.

**Comment by Fuco1** [comment]
@atheriel Thanks, will do!

**Pull request merged**
