### PR TITLE
Feature: Add custom property access

### PR DESCRIPTION
**Pull request by smartintruesdell**
I ran into a similar need to the one expressed in #23, and put together a solution that worked.

I'm SUPER NEW to elisp and emacs contributions in general (first ever elisp pull request!), so I'd really appreciate any feedback you can provide,

### CODE REVIEW

**Comment by smartintruesdell** [comment]
I tried my solution with a prefix argument to run it over only one org buffer, and I didn't get the result I expected. I'll keep poking at this.

**Comment by smartintruesdell** [comment]
Resolved my issue, now it correctly retrieves inherited properties.

**Comment by atheriel** [comment]
This implementation makes sense to me. Can you please add a test?

**Comment by smartintruesdell** [comment]
> Can you please add a test?

Done! My first elisp regression test too. :+1:

Thankfully this did expose a bug, which is also resolved.

**Pull request merged**
