### PR TITLE
Issue3: Adding headline ancestors to the task headline

### PR DESCRIPTION
**Pull request by btljuice**
Hi,

Here's a modification that adds the headline ancestors to the task headline. I add two custom variables, one to enable/disable the addition of the headline ancestors to the task headline, and another to control the headline separators.

I also added a minimal test case (issue-3.org) to the test suite.

Feel free to modify it and/or give me comments about it.

Cheers!

### CODE REVIEW

**Comment by btljuice** [comment]
Just to let your know I added a fix to my pull request. I misordered the call )org-clock-csv--escape), applying it on each headline entry instead of whole headline path sequence. The latest is on 3aa7fcf

**Comment by atheriel** [comment]
Thanks for submitting this! Headline ancestry is a nice feature to have. I have two thoughts about this approach.

The first is that this will fail on headlines with `/` characters in them, but I think this could be fixed by escaping them (e.g. transforming any `/` into `//` in headlines). This is a simple fix, and I'd be happy to merge and add it later.

The second, and more substantial issue is that I don't think ancestry information should be in the `task` column, because this would make consuming the CSV files much more difficult (since you'd need to parse the `task` column). Rather, I think it makes more sense to have a separate column containing parent headlines.

Does this make sense to you?

**Comment by btljuice** [comment]
Thanks for foreseeing about the / character. I don't have much knowledge on which character needs escaping, and which does not.

I actually totally agree with you on the second point. As I was finishing my fix, I thought too that maybe it would be better to have the headline ancestors in another csv column. One of my prior trial was actually like that. I have no problem making that change and resubmitting a pull request. It's not so complicated to do.

In the same line of thought:

1. What column header name would you like for the headline ancestors ? ("headlines", "parent headlines", "ancestors"?, etc.)
2. In which position would you like me to add the column header ? (before task, after task, at the end, etc.)
3. What default character is a more appropriate for the "org-clock-csv-headline-separator" variable?

Thanks for the update. I'm waiting for your answers.

**Comment by btljuice** [comment]
In the mean time, my latest commit  028430b adds a "parents" column at the right of the "task" column. 

The "task" column contains now its original information: the task's headline.
The "parents" contains the headline ancestor's of "task" with '/' as the default separator.

Changing your personal tastes to my previous questions should pause any problem.

**Comment by atheriel** [comment]
This looks good to me. I think `/` is good, and `parents` is good as well. I'll file an issue for the escaping corner case.

**Pull request merged**
